#!/usr/bin/env bash

## Runs PHPCS on modules 
##
## Usage: fin php-cs 

fin run phpcs \
    --standard="Wordpress" \
    --extensions="php,module,inc,install,test,profile,theme" \
    --ignore="*.features.*,*.pages*.inc" \
    src/modules
